external:
  percentage:
    url: ${PERCENTAGE_API_URL:http://localhost:3100/api/percentage}

spring:

  flyway:
    url: ${FLYWAY_DATABASE_URL:jdbc:postgresql://localhost:5437/postgres}
    locations: classpath:db/postgres/migration

  data:
    redis:
      host: ${CACHE_HOST:localhost}
      port: ${CACHE_PORT:6380}

  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5437/postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}

cache:
  ttl:
    percentage: 30

logging:
  level:
    org:
      springframework:
        cache: TRACE
    reactor:
      netty:
        http:
          client:
            HttpClient: DEBUG

rate:
  limit:
    unit: MINUTES
    amount: 3

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
