external:
  percentage:
    url: http://localhost:3100/api/percentage

spring:

  flyway:
    url: jdbc:postgresql://localhost:5437/postgres?sslmode=disable
    locations: classpath:db/postgres/migration

  data:
    postgres:
      host: localhost
      port: 5437
      username: postgres
      password: postgres
      database: postgres

    redis:
      host: localhost
      port: 6380

  r2dbc:
    url: r2dbc:postgresql://localhost:5437/postgres?sslmode=disable
    username: postgres
    password: postgres

cache:
  ttl:
    # expressed in minutes
    percentage: 30

logging:
  level:
    org:
      springframework:
        cache: TRACE
    reactor:
      netty:
        http:
          client:
            HttpClient: DEBUG

rate:
  limit:
    perMinute: 3
